import { env } from "cloudflare:workers";
import { getPrivilege, audit } from "../authz";

type CasaItem={id:string;title:string;kind:"publicación"|"curso"|"turismo"|"convenio";text:string;schedule?:string;level?:string;image?:string};
const defaults:CasaItem[]=[
{id:"arte",kind:"publicación",title:"Arte, cultura y comunidad",text:"Un espacio para desarrollar la creatividad, aprender nuevas disciplinas y fortalecer la convivencia sindical.",image:"/casa-cultura-arte.svg"},
{id:"idiomas",kind:"curso",title:"Idiomas",text:"Inglés, francés y alemán para niñas, niños, adolescentes, adultos y jubilados.",schedule:"Consulta horarios y grupos disponibles.",level:"Todos los niveles",image:"/casa-cultura-idiomas.svg"},
{id:"musica",kind:"curso",title:"Música",text:"Guitarra, rondalla, coro, batería y guitarra eléctrica.",schedule:"Clases entre semana y sábados.",level:"Inicial e intermedio",image:"/casa-cultura-musica.svg"},
{id:"artes",kind:"curso",title:"Artes escénicas y visuales",text:"Teatro, danza, folclórica, arte y pintura, fotografía y amigurumis.",schedule:"Horarios sujetos a apertura de grupos.",level:"Niñas, niños, jóvenes, adultos y jubilados",image:"/casa-cultura-artes.svg"},
{id:"turismo",kind:"turismo",title:"Turismo sindical",text:"Próximamente encontrarás recorridos, destinos, actividades culturales y promociones para disfrutar Puebla y México.",schedule:"Publicaremos calendario, costos y cupos en este espacio.",image:"/casa-cultura-portada.svg"}];
async function items(){try{const r=await env.DB.prepare("SELECT id,title,kind,text,schedule,level,image FROM casa_cultura_items WHERE active=1 ORDER BY sort_order,created_at").all<CasaItem>();return r.results.length?r.results:defaults}catch{return defaults}}
async function manager(request:Request){const p=await getPrivilege(request);return p&&(p.canAdmin||p.canManageUnionCalendar)?p:null}
function clean(v:unknown,n=2000){return String(v??"").trim().slice(0,n)}
export async function GET(){return Response.json({items:await items()},{headers:{"cache-control":"no-store"}})}
export async function POST(request:Request){const p=await manager(request);if(!p)return Response.json({error:"Acceso exclusivo para Secretaría de Cultura o administración."},{status:403});const b=await request.json() as Partial<CasaItem>;if(!clean(b.title)||!clean(b.text))return Response.json({error:"Título y descripción son obligatorios."},{status:400});const id=crypto.randomUUID();await env.DB.prepare("INSERT INTO casa_cultura_items(id,title,kind,text,schedule,level,image,updated_by) VALUES(?,?,?,?,?,?,?,?)").bind(id,clean(b.title,180),clean(b.kind,20)||"publicación",clean(b.text),clean(b.schedule,300)||null,clean(b.level,300)||null,clean(b.image,800)||null,p.actor).run();await audit(p.actor,"casa_cultura.create","casa_cultura_item",id,clean(b.title,180));return Response.json({items:await items()})}
export async function PUT(request:Request){const p=await manager(request);if(!p)return Response.json({error:"Acceso exclusivo para Secretaría de Cultura o administración."},{status:403});const b=await request.json() as Partial<CasaItem>;const id=clean(b.id,80);if(!id||!clean(b.title)||!clean(b.text))return Response.json({error:"Contenido incompleto."},{status:400});await env.DB.prepare("UPDATE casa_cultura_items SET title=?,kind=?,text=?,schedule=?,level=?,image=?,updated_by=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(clean(b.title,180),clean(b.kind,20),clean(b.text),clean(b.schedule,300)||null,clean(b.level,300)||null,clean(b.image,800)||null,p.actor,id).run();await audit(p.actor,"casa_cultura.update","casa_cultura_item",id,clean(b.title,180));return Response.json({items:await items()})}
